apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-test
resources:
  - ../../../../base/kustomize/backend-demo-app
  - namespace.yaml
  

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: backend
    path: backend-gateway-binding.yaml
