apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-test
resources:
  - ../../../../base/kustomize/backend-demo-app
  - namespace.yaml
  

patchesStrategicMerge:
  - backend-gateway-binding.yaml
