# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - ../../../base/prometheus

# helmCharts:
#   - name: kube-prometheus-stack
#     includeCRDs: false
#     valuesFile: values-prod.yaml