apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-prod
resources:
  - ../../../../base/kustomize/elastic/cluster
  - namespace.yaml
  - elastic-exporter.yaml
  - elastic-exporter-service.yaml
  - servicemonitor.yaml