# namespace: cert-manager

# config:
#   apiVersion: controller.config.cert-manager.io/v1alpha1
#   kind: ControllerConfiguration
#   enableGatewayAPI: true
  
# cert-manager:
#   installCRDs: true
#   extraArgs:
#     - --feature-gates=ExperimentalGatewayAPISupport=true

