apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - gatewayclass.yaml


patches:
  - path: gateway-address-patch.yaml
    target:
      kind: Gateway
      name: prod-gateway
      namespace: envoy-system-prod